### ISSUE TITLE
Screen: Gameplay

### ISSUE THREAD

**Issue by Eweer** [xGauss05/RPG-Game-Project#4]
- [x] Implement a TOWN map with at least 3 locations to visit (i.e. House, Tavern, Graveyard...)
- [x] Implement at least **2 Playable Characters**, available as the base Team Party
- [x] Implement at least **3 NPC Characters** (town people, wizard, tavern…)
- [x] Implement at least **4 Dialogs** with branching with NPC characters
- [x] INPUTS: Keyboard/Gamepad inputs supported
- [x] UI: PAUSE menu available on pause
- [x] AUDIO: Music track specific for the screen
- [x] AUDIO: Music effects fade-in/fade-out, lower volume on PAUSE

**Comment by xGauss05** [comment]
Done
